#ifndef VIEWER_H
#define VIEWER_H

#include <string>
#include <vector>
using namespace std;

class Viewer {
public:
    Viewer();
    Viewer(int _userID, string _un, string _pw, string _priv, string _desc, string _selfPic);

    //Getters and setters
    int getUserID();
    void setUserID(int);
    string getUn();
    void setUn(string);
    string getPw();
    void setPw(string);
    string getPrivelege();
    void setPrivelege(string);
    string getDescription();
    void setDescription(string);
    string getSelfPic();
    void setSelfPic(string);
    string getUniquePW();
    void setUniquePW(string);

protected:
    //Attributes that all accounts have
    string pw;
    string un;
    string privelege;
    int userID;
    string description;
    string selfPic;
    //This is the password the new user needs to create an account. It is generated by the admin
    string uniquePW;

};

#endif // VIEWER_H
